name: Make Keystore

on: workflow_dispatch

jobs:
  gen:
    runs-on: ubuntu-latest
    steps:
      - name: Generate keystore
        run: |
          keytool -genkeypair -v \
            -keystore keystore.jks \
            -alias tikdown \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -storepass "${{ secrets.KEYSTORE_PASSWORD }}" \
            -keypass "${{ secrets.KEY_PASSWORD }}" \
            -dname "CN=TikDown, OU=Dev, O=TikDown, L=Cairo, ST=Cairo, C=EG"
          base64 -w 0 keystore.jks > keystore_base64.txt

      - uses: actions/upload-artifact@v4
        with:
          name: keystore-output
          path: keystore_base64.txt
